#!/usr/bin/env python3

# beginning

from bs4 import BeautifulSoup
import requests
import requests.exceptions
import urllib.parse
from collections import deque
import re

user_url = str(input('[+] Enter target URL to scan: '))
urls = deque([user_url])

scraped_urls = set()
email = set()

count = 0
try:
    while len(urls):
        count += 1
        if count == 100:

           break
        url = urls.popleft()
        scraped_urls.add(url)

        parts = urllib.parse.urlsplit(url)
        base_url = '{0.scheme}://{0.netloc}'.format(parts)

        # Modify the path extraction to handle URLs more robustly
        path = url[url.rfind('/') + 1:] if '/' in parts.path else url
        print('[%d] Processing %s' % (count, url))
        try:
            response = requests.get(url)

        except (requests.exceptions.MissingSchema, requests.exceptions.ConnectionError):
            continue

        new_emails = set(re.findall(r'[a-z0-9\. \-+_]+@[a-z0-9\. \-+_]+\.[a-z]+', response.text, re.IGNORECASE))
        email.update(new_emails)

        soup = BeautifulSoup(response.text, features="lxml")

        for anchor in soup.find_all("a"):
       link = anchor.attrs.get('href', '')
            if link.startswith('/'):
                link = base_url + link
            elif not link.startswith('http'):
                link = path + link
            if link not in urls and link not in scraped_urls:
                urls.append(link)

except KeyboardInterrupt:
    print('[-] Closing!')

for mail in email:
    print(mail)
